language: php

os:
  - linux

jobs:
  include:
    - stage: test
      php: "7.0"
      env:
        - TYPO3_VERSION=^8
    - stage: test
      php: "7.1"
      env:
        - TYPO3_VERSION=^8
    - stage: test
      php: "7.2"
      env:
        - TYPO3_VERSION=^8
    - stage: test
      php: "7.2"
      env:
        - TYPO3_VERSION=^9

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - "$HOME/.composer/cache"

notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      - secure: "qcoD6vn+9P7VES8d8QMusGsFadA+QLDvE+kRVvbX32/FEbTQMcC4NwbP0B8GwfQ6W3N7olegiprDO7hDFmPWxCPpLFvT8YHM8GpOOg3pCKcvHeBGlWGuVtsJQgJ6fmCgFnTRNyon7YMQenDonA+ExkvZ1/Lfd/J3H/rGdOU93YdHoTtphWSfhiOd8q6JCoKmlsDiFrgpcljp+z67ZXh6dSGmKEyCI8vsEm0gNC9R5OdLJz48nMfZ7YhsiCgPuaEz2YlimJHSomD0AXEZJ5fQPG3d7g6uhxP6gIZeWFYRr54ODqEMZGKKqUHwJoUK4B3j5k2bbifjIN6gIGHvOQcJLWPrW5R3be6YCbSedIA5kdpZcgQXj3ROXJirCqwlc7vxsecoH3Ai+REv6VJn5KKkDMPOvJtVE85iHOdLUQ0ugLcodL2z3mue3+33wMwYcr7PaEBD9BOAQEax+kjTtxmIRoH22hqMdEqDv9do9B5b74wu6b5x52klIRzs1pj3ZKi0PCjISGFlXKX5Nh8IZIPEHqO9ihry88TLnmP6wFmT7XTvEt7YB8tR7mdU/G7n+RMrXq5OkU1KFDG4FJq1kxXAbhcT9byaCd+q4r0g/fW3SsvwsE0t8tf+lTd5vrH+meCZ22iHDYm7/VtWLNpTcxCi0SOWj0fu8LuNAX6nyQj1oEU="

before_install:
  - if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi
  - composer self-update

install:
  - >
    composer config minimum-stability dev;
    composer config prefer-stable true;
  - while true; do echo "..."; sleep 60; done &
  - composer require typo3/minimal=$TYPO3_VERSION
  - kill %1
  - mkdir -p .Build/public/typo3conf/ext/
  - if [ ! -L .Build/public/typo3conf/ext/schooldirectory ]; then ln -snvf ../../../../. .Build/public/typo3conf/ext/schooldirectory; fi
  - echo 'date.timezone = "Europe/Paris"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - git checkout composer.json
  - export TYPO3_PATH_ROOT=$PWD/.Build/public

script:
  - >
    if [ -d "Tests/Unit" ]; then
      echo;
      echo "Running unit tests";
      echo;
      echo;
      .Build/bin/phpunit --color --bootstrap .Build/vendor/nimut/testing-framework/res/Configuration/UnitTestsBootstrap.php Tests/Unit/;
    fi

  - >
    echo;
    echo "Running parallel";
    echo;
    echo;
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;;

  - >
    echo;
    echo "Running PHP Coding Standards Fixer checks";
    echo;
    echo;
    .Build/bin/php-cs-fixer fix --config=Build/.php_cs.php --dry-run --using-cache=no -v --diff;
