services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JWeiland\Schooldirectory\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  JWeiland\Schooldirectory\EventListener\AddPaginatorEventListener:
    tags:
      - name: event.listener
        event: JWeiland\Schooldirectory\Event\PostProcessFluidVariablesEvent

  JWeiland\Schooldirectory\EventListener\AddGlossaryEventListener:
    tags:
      - name: event.listener
        event: JWeiland\Schooldirectory\Event\PostProcessFluidVariablesEvent
        after: JWeiland\Schooldirectory\EventListener\AddPaginatorEventListener

  JWeiland\Schooldirectory\EventListener\AddStoragePagesEventListener:
    tags:
      - name: event.listener
        event: JWeiland\Schooldirectory\Event\PostProcessFluidVariablesEvent
